name: bel_adn
description: bel_adn is the common library for the frontend of the "magnifique couple" project. 
version: 2.0.0
homepage: https://github.com/shalien/bel_adn

environment:
  sdk: '>=3.0.0 <4.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^0.13.5
  meta: ^1.8.0
