name: bel_adn
description: bel_adn is the common library for the frontend of the "magnifique couple" project. 
version: 5.0.0
homepage: https://github.com/shalien/bel_adn
repository: https://github.com/shalien/bel_adn.git

environment:
  sdk: '>=3.0.0 <4.0.0'


dev_dependencies:
  lints: ^4.0.0
  sha_env: ^3.0.0
  test: ^1.24.4

dependencies:
  http: ^1.2.2
  meta: ^1.15.0
