name: bel_adn
description: bel_adn is the common library for the frontend of the "magnifique couple" project. 
version: 4.2.1
homepage: https://github.com/shalien/bel_adn
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.4
  sha_env:
    git: https://github.com/shalien/sha_env.git

dependencies:
  http: any
  meta: any
