name: bel_adn
description: bel_adn is the common library for the frontend of the "magnifique couple" project. 
version: 2.0.52
homepage: https://github.com/shalien/bel_adn
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.4
dependencies:
  http: ^1.0.0
  meta: ^1.8.0
  sha_env: 
    git: https://github.com/shalien/sha_env.git